DROP TABLE IF EXISTS pessoa CASCADE;
DROP TABLE IF EXISTS dependente CASCADE;

CREATE TABLE pessoa (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	nome VARCHAR(100) NOT NULL,
	cpf VARCHAR(100) NOT NULL
);
ALTER TABLE pessoa ADD CONSTRAINT pk_pessoa PRIMARY KEY (id);
ALTER TABLE pessoa ADD CONSTRAINT uk_pessoa_cpf UNIQUE (cpf);

CREATE TABLE dependente (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	nome VARCHAR(100) NOT NULL,
	data_nascimento DATE NOT NULL,
	pessoa_id BIGINT NOT NULL
);
ALTER TABLE dependente ADD CONSTRAINT pk_dependente PRIMARY KEY (id);
ALTER TABLE dependente ADD CONSTRAINT fk_dependente_pessoa FOREIGN KEY (pessoa_id) REFERENCES pessoa;

INSERT INTO pessoa (nome, cpf) VALUES ('Maria do Carmo', '123.123.123-12');
INSERT INTO pessoa (nome, cpf) VALUES ('José Pedroza', '543.345.24-22');
INSERT INTO pessoa (nome, cpf) VALUES ('Carla Silva', '532.675.347-87');

INSERT INTO dependente (nome, data_nascimento, pessoa_id) VALUES ('José Júnior', '2019-02-01', 2);
INSERT INTO dependente (nome, data_nascimento, pessoa_id) VALUES ('Hanna Pedroza', '2016-08-10', 2);
INSERT INTO dependente (nome, data_nascimento, pessoa_id) VALUES ('Michele do Carmo', '2019-02-01', 1);
